name: dart_curses
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.18.0 <4.0.0'

# Trigger generation with `dart run ffigen`
ffigen:
  output: 'lib/src/ncurses.g.dart'
  headers:
    entry-points:
      - '../third_party/ncurses/include/curses.h'
  comments:
    style: any
    length: full
  sort: true
  preamble: |
    // ignore_for_file: camel_case_types, non_constant_identifier_names
  structs:
    member-rename:
      '_win_st':
        '_(.*)': '$1'

# Add regular dependencies here.
dependencies:
  ffi: 2.0.1
  path: 1.8.3

dev_dependencies:
  lints: 2.0.0
  test: 1.21.0
  # requires libclang-dev on dev machines
  ffigen: 7.2.5
