name: term_ui
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0-218.0.dev <4.0.0'

# Add regular dependencies here.
dependencies:
  dart_curses:
    path:
      ../dart_curses
  meta: any

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
